### ISSUE TITLE
Spellchecking in input boxes

### ISSUE THREAD

**Issue by Jonty** [irccloud/irccloud-desktop#11]
https://github.com/atom/electron/pull/942

**Comment by russss** [comment]
We can do that with electron-spell-check-provider as [documented here](https://github.com/mixmaxhq/electron-spell-check-provider#but-how-do-i-show-spelling-suggestions-in-the-context-menu). I think it should probably be optional though.

**Comment by russss** [comment]
I've added this based on electron-spell-check-provider. There are a few issues:

* It's en_US only at the moment
* We should have this controlled by a setting, but it doesn't seem to be possible to disable the spellchecker once it's registered with the webFrame (short of completely killing and restarting the window).
* The right-click menu integration is quite shonky and needs improving (it's unclear how much this is due to the underlying implementation).

**Comment by jwheare** [comment]
This is fine for now.

**Comment by paroxp** [comment]
Is it possible, to add different directories yet?
