### ISSUE TITLE
Support for new emojis

### ISSUE THREAD

**Issue by moopie** [irccloud/irccloud-desktop#130]
![image](https://user-images.githubusercontent.com/271154/48258587-15299a80-e41e-11e8-8eb8-1f03c626eea0.png)

As you can see, emojis that display fine in chrome don't get displayed in irccloud-desktop
Also, on an unrelated note: chrome now lets you choose emojis in a text field, wonder if that can be ported
https://www.theverge.com/2018/4/6/17206312/google-chrome-emoji-desktop-shortcut-right-click
Example:
![image](https://user-images.githubusercontent.com/271154/48258806-bb75a000-e41e-11e8-8862-f478515bba36.png)

**Comment by jwheare** [comment]
This is because the desktop app uses an older version of Chromium without up to date emoji support. This will be fixed in due course as electron gets updated.

There is however a workaround we do for every emoji update to ease support across all platforms, and isn't specific to the desktop app. We usually have to wait for the upstream emoji data library before we can do it. e.g. https://github.com/iamcal/emoji-data/pull/146

Closing this since it's not really desktop specific.

Also, we have an emoji picker in the chat bar already.

![image](https://user-images.githubusercontent.com/49224/48413551-f722a980-e73f-11e8-922b-c58e4cea5082.png)
