### ISSUE TITLE
32-bit Windows is not supported

### ISSUE THREAD

**Issue by ghost** [irccloud/irccloud-desktop#36]
[log.txt](https://github.com/irccloud/irccloud-desktop/files/285255/log.txt)

Good evening,

Here a little issue while installing the application which stopped the installation

**Comment by russss** [comment]
This looks like it's because our Windows build is 64-bit only, and your machine is 32-bit. I can't offer any immediate fixes unfortunately, but I'll keep this ticket open.

**Comment by jwheare** [comment]
@johnfra is this still happening with the latest release (v0.1.9) downloaded from http://dekstop.irccloud.com ?

**Comment by johnfra** [comment]
Hello, 
The installation is longer than before, but near the end an error still happening

**Comment by jwheare** [comment]
Could you provide an updated log please?

**Comment by johnfra** [comment]
@jwheare Sure:
[SquirrelSetup.txt](https://github.com/irccloud/irccloud-desktop/files/344747/SquirrelSetup.txt)

**Comment by jwheare** [comment]
This looks like a known issue with the Installer library. See https://github.com/Squirrel/Squirrel.Windows/issues/698#issuecomment-225895045

Are you running antivirus? Does turning it off temporarily allow you to install?

**Comment by johnfra** [comment]
I just try by turning my antivirus (Avast) off, however the same problem is happening

**Comment by jwheare** [comment]
OK, on further research, that linked issue appears unrelated, it does still look like this is a 32 bit issue.

Notes for us:
With our current setup we can't currently support dual architecture releases due to an issue with our update server: https://github.com/GitbookIO/nuts/issues/32

One option is to only build 32-bit binaries on Windows, or else switch to a different update server.

Other relevant issues:
https://github.com/electron-userland/electron-builder/issues/359#issuecomment-214812342
https://github.com/electron-userland/electron-builder/issues/439#issuecomment-221523712

**Comment by jwheare** [comment]
This should hopefully be resolved by #45

**Comment by jwheare** [comment]
The next release should resolve this.

**Comment by ant298** [comment]
I have changed of computer. As a consequence, I won't be able to help you to test. The current PC didn't have this problem. Sorry!

**Comment by jwheare** [comment]
Fixed in the latest release: https://github.com/irccloud/irccloud-desktop/releases/tag/v0.4.0
